@currentUserHandle = Meteor.subscribe("currentUser")
@widgetsHandle = Meteor.subscribe("widgets")
@membersHandle = Meteor.subscribe("members")
@feedbacksHandle = Meteor.subscribe("feedbacks")
@domainsHandle = Meteor.subscribe("domains")